<a href="https://colab.research.google.com/github/lucarso120/Data-science-projects/blob/master/bank_client_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import sklearn

**FIRST STEP**

Split data into features and labels


In [ ]:
data = pd.read_csv("/content/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
features = data.iloc[:, 3:-1].values
labels = data.iloc[:, -1].values
print(features)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


**SECOND STEP**

Clean the data. Transfor non-numerical values into numerical for the gender column



In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
features[:, 2] = labelencoder.fit_transform(features[:, 2])
print(features)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**ALTERNATIVE MODE**
Using map function. 

In [ ]:
#features = data.iloc[:, 3:-1]
#labels = data.iloc[:, -1]
#features.Gender = features.Gender.map({'Male': 0, 'Female':1})
#print(features.Gender)

**HOT ENCONDING**
For the nationality


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder ='passthrough')
features = np.array(transformer.fit_transform(features))
print(features)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


**SPLIT INTO TRAINING AND TEST**


In [ ]:
from sklearn.model_selection import train_test_split

features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = .2, random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)


**Build ANN**

In [ ]:
artnn = tf.keras.models.Sequential()
artnn.add(tf.keras.layers.Dense( 6, activation='relu'))
artnn.add(tf.keras.layers.Dense( 6, activation='relu'))
artnn.add(tf.keras.layers.Dense( 1, activation='sigmoid'))


In [ ]:
artnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**TRAINING**


In [ ]:
artnn.fit(features_train, labels_train, batch_size = 32, epochs=100)

In [ ]:
print(artnn.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)